### Test Root Endpoint
GET http://localhost:3000/
Accept: application/json

###

### Register a New User
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "new_user3",
    "email": "new_user3@example.com",
    "password": "Password1234"
}

###

### Login a User
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "new_user3",
    "password": "Password1234"
}

###

### Get User Profile
GET http://localhost:3000/getUserProfile?username=new_user3
Accept: application/json

###

### Get User Tasks
GET http://localhost:3000/api/users-tasks?username=new_user3
Accept: application/json